// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sf/substreams/foundational-store/service/v2/service.proto

package pbserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/streamingfast/substreams/pb/sf/substreams/foundational-store/service/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StoreName is the fully-qualified name of the Store service.
	StoreName = "sf.substreams.foundational_store.service.v2.Store"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StoreGetProcedure is the fully-qualified name of the Store's Get RPC.
	StoreGetProcedure = "/sf.substreams.foundational_store.service.v2.Store/Get"
	// StoreGetAllProcedure is the fully-qualified name of the Store's GetAll RPC.
	StoreGetAllProcedure = "/sf.substreams.foundational_store.service.v2.Store/GetAll"
	// StoreGetFirstProcedure is the fully-qualified name of the Store's GetFirst RPC.
	StoreGetFirstProcedure = "/sf.substreams.foundational_store.service.v2.Store/GetFirst"
	// StoreGetAllFirstProcedure is the fully-qualified name of the Store's GetAllFirst RPC.
	StoreGetAllFirstProcedure = "/sf.substreams.foundational_store.service.v2.Store/GetAllFirst"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	storeServiceDescriptor           = v2.File_sf_substreams_foundational_store_service_v2_service_proto.Services().ByName("Store")
	storeGetMethodDescriptor         = storeServiceDescriptor.Methods().ByName("Get")
	storeGetAllMethodDescriptor      = storeServiceDescriptor.Methods().ByName("GetAll")
	storeGetFirstMethodDescriptor    = storeServiceDescriptor.Methods().ByName("GetFirst")
	storeGetAllFirstMethodDescriptor = storeServiceDescriptor.Methods().ByName("GetAllFirst")
)

// StoreClient is a client for the sf.substreams.foundational_store.service.v2.Store service.
type StoreClient interface {
	// Get retrieves a single value by key at a specific block number
	Get(context.Context, *connect.Request[v2.GetRequest]) (*connect.Response[v2.GetResponse], error)
	// GetAll retrieves multiple values by keys at a specific block number
	GetAll(context.Context, *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error)
	GetFirst(context.Context, *connect.Request[v2.GetFirstRequest]) (*connect.Response[v2.GetResponse], error)
	GetAllFirst(context.Context, *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error)
}

// NewStoreClient constructs a client for the sf.substreams.foundational_store.service.v2.Store
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStoreClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StoreClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &storeClient{
		get: connect.NewClient[v2.GetRequest, v2.GetResponse](
			httpClient,
			baseURL+StoreGetProcedure,
			connect.WithSchema(storeGetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAll: connect.NewClient[v2.GetAllRequest, v2.GetAllResponse](
			httpClient,
			baseURL+StoreGetAllProcedure,
			connect.WithSchema(storeGetAllMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getFirst: connect.NewClient[v2.GetFirstRequest, v2.GetResponse](
			httpClient,
			baseURL+StoreGetFirstProcedure,
			connect.WithSchema(storeGetFirstMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAllFirst: connect.NewClient[v2.GetAllRequest, v2.GetAllResponse](
			httpClient,
			baseURL+StoreGetAllFirstProcedure,
			connect.WithSchema(storeGetAllFirstMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// storeClient implements StoreClient.
type storeClient struct {
	get         *connect.Client[v2.GetRequest, v2.GetResponse]
	getAll      *connect.Client[v2.GetAllRequest, v2.GetAllResponse]
	getFirst    *connect.Client[v2.GetFirstRequest, v2.GetResponse]
	getAllFirst *connect.Client[v2.GetAllRequest, v2.GetAllResponse]
}

// Get calls sf.substreams.foundational_store.service.v2.Store.Get.
func (c *storeClient) Get(ctx context.Context, req *connect.Request[v2.GetRequest]) (*connect.Response[v2.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// GetAll calls sf.substreams.foundational_store.service.v2.Store.GetAll.
func (c *storeClient) GetAll(ctx context.Context, req *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error) {
	return c.getAll.CallUnary(ctx, req)
}

// GetFirst calls sf.substreams.foundational_store.service.v2.Store.GetFirst.
func (c *storeClient) GetFirst(ctx context.Context, req *connect.Request[v2.GetFirstRequest]) (*connect.Response[v2.GetResponse], error) {
	return c.getFirst.CallUnary(ctx, req)
}

// GetAllFirst calls sf.substreams.foundational_store.service.v2.Store.GetAllFirst.
func (c *storeClient) GetAllFirst(ctx context.Context, req *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error) {
	return c.getAllFirst.CallUnary(ctx, req)
}

// StoreHandler is an implementation of the sf.substreams.foundational_store.service.v2.Store
// service.
type StoreHandler interface {
	// Get retrieves a single value by key at a specific block number
	Get(context.Context, *connect.Request[v2.GetRequest]) (*connect.Response[v2.GetResponse], error)
	// GetAll retrieves multiple values by keys at a specific block number
	GetAll(context.Context, *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error)
	GetFirst(context.Context, *connect.Request[v2.GetFirstRequest]) (*connect.Response[v2.GetResponse], error)
	GetAllFirst(context.Context, *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error)
}

// NewStoreHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStoreHandler(svc StoreHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	storeGetHandler := connect.NewUnaryHandler(
		StoreGetProcedure,
		svc.Get,
		connect.WithSchema(storeGetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	storeGetAllHandler := connect.NewUnaryHandler(
		StoreGetAllProcedure,
		svc.GetAll,
		connect.WithSchema(storeGetAllMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	storeGetFirstHandler := connect.NewUnaryHandler(
		StoreGetFirstProcedure,
		svc.GetFirst,
		connect.WithSchema(storeGetFirstMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	storeGetAllFirstHandler := connect.NewUnaryHandler(
		StoreGetAllFirstProcedure,
		svc.GetAllFirst,
		connect.WithSchema(storeGetAllFirstMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.substreams.foundational_store.service.v2.Store/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StoreGetProcedure:
			storeGetHandler.ServeHTTP(w, r)
		case StoreGetAllProcedure:
			storeGetAllHandler.ServeHTTP(w, r)
		case StoreGetFirstProcedure:
			storeGetFirstHandler.ServeHTTP(w, r)
		case StoreGetAllFirstProcedure:
			storeGetAllFirstHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStoreHandler returns CodeUnimplemented from all methods.
type UnimplementedStoreHandler struct{}

func (UnimplementedStoreHandler) Get(context.Context, *connect.Request[v2.GetRequest]) (*connect.Response[v2.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.substreams.foundational_store.service.v2.Store.Get is not implemented"))
}

func (UnimplementedStoreHandler) GetAll(context.Context, *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.substreams.foundational_store.service.v2.Store.GetAll is not implemented"))
}

func (UnimplementedStoreHandler) GetFirst(context.Context, *connect.Request[v2.GetFirstRequest]) (*connect.Response[v2.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.substreams.foundational_store.service.v2.Store.GetFirst is not implemented"))
}

func (UnimplementedStoreHandler) GetAllFirst(context.Context, *connect.Request[v2.GetAllRequest]) (*connect.Response[v2.GetAllResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sf.substreams.foundational_store.service.v2.Store.GetAllFirst is not implemented"))
}
