// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: sf/remotebuild/v1/remotebuild.proto

package pbbuildv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Zip file with source code to unzip in a temporary directory.
	SourceCode []byte `protobuf:"bytes,1,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	// Environment vars, passed to `exec.Command()`
	Env []string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	// Double star glob pattern to collect after the build has succeeded
	CollectPattern string `protobuf:"bytes,3,opt,name=collect_pattern,json=collectPattern,proto3" json:"collect_pattern,omitempty"`
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_remotebuild_v1_remotebuild_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_remotebuild_v1_remotebuild_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_sf_remotebuild_v1_remotebuild_proto_rawDescGZIP(), []int{0}
}

func (x *BuildRequest) GetSourceCode() []byte {
	if x != nil {
		return x.SourceCode
	}
	return nil
}

func (x *BuildRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *BuildRequest) GetCollectPattern() string {
	if x != nil {
		return x.CollectPattern
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Logs  string `protobuf:"bytes,2,opt,name=logs,proto3" json:"logs,omitempty"`
	// Return only the .spkg for the output
	Artifacts []*BuildResponse_BuildArtifact `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_remotebuild_v1_remotebuild_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_remotebuild_v1_remotebuild_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_sf_remotebuild_v1_remotebuild_proto_rawDescGZIP(), []int{1}
}

func (x *BuildResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BuildResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *BuildResponse) GetArtifacts() []*BuildResponse_BuildArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type BuildResponse_BuildArtifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content  []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *BuildResponse_BuildArtifact) Reset() {
	*x = BuildResponse_BuildArtifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_remotebuild_v1_remotebuild_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildResponse_BuildArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse_BuildArtifact) ProtoMessage() {}

func (x *BuildResponse_BuildArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_sf_remotebuild_v1_remotebuild_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse_BuildArtifact.ProtoReflect.Descriptor instead.
func (*BuildResponse_BuildArtifact) Descriptor() ([]byte, []int) {
	return file_sf_remotebuild_v1_remotebuild_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BuildResponse_BuildArtifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BuildResponse_BuildArtifact) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_sf_remotebuild_v1_remotebuild_proto protoreflect.FileDescriptor

var file_sf_remotebuild_v1_remotebuild_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x66, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x66, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x6a, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x6e, 0x22, 0xce, 0x01, 0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x6f, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73,
	0x12, 0x4c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x66, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x1a, 0x45,
	0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x5c, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x05, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x1f,
	0x2e, 0x73, 0x66, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x73, 0x66, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x66, 0x61, 0x73, 0x74, 0x2f,
	0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x66, 0x2f, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sf_remotebuild_v1_remotebuild_proto_rawDescOnce sync.Once
	file_sf_remotebuild_v1_remotebuild_proto_rawDescData = file_sf_remotebuild_v1_remotebuild_proto_rawDesc
)

func file_sf_remotebuild_v1_remotebuild_proto_rawDescGZIP() []byte {
	file_sf_remotebuild_v1_remotebuild_proto_rawDescOnce.Do(func() {
		file_sf_remotebuild_v1_remotebuild_proto_rawDescData = protoimpl.X.CompressGZIP(file_sf_remotebuild_v1_remotebuild_proto_rawDescData)
	})
	return file_sf_remotebuild_v1_remotebuild_proto_rawDescData
}

var file_sf_remotebuild_v1_remotebuild_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sf_remotebuild_v1_remotebuild_proto_goTypes = []interface{}{
	(*BuildRequest)(nil),                // 0: sf.remotebuild.v1.BuildRequest
	(*BuildResponse)(nil),               // 1: sf.remotebuild.v1.BuildResponse
	(*BuildResponse_BuildArtifact)(nil), // 2: sf.remotebuild.v1.BuildResponse.BuildArtifact
}
var file_sf_remotebuild_v1_remotebuild_proto_depIdxs = []int32{
	2, // 0: sf.remotebuild.v1.BuildResponse.artifacts:type_name -> sf.remotebuild.v1.BuildResponse.BuildArtifact
	0, // 1: sf.remotebuild.v1.BuildService.Build:input_type -> sf.remotebuild.v1.BuildRequest
	1, // 2: sf.remotebuild.v1.BuildService.Build:output_type -> sf.remotebuild.v1.BuildResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_remotebuild_v1_remotebuild_proto_init() }
func file_sf_remotebuild_v1_remotebuild_proto_init() {
	if File_sf_remotebuild_v1_remotebuild_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sf_remotebuild_v1_remotebuild_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_remotebuild_v1_remotebuild_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_remotebuild_v1_remotebuild_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildResponse_BuildArtifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sf_remotebuild_v1_remotebuild_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_remotebuild_v1_remotebuild_proto_goTypes,
		DependencyIndexes: file_sf_remotebuild_v1_remotebuild_proto_depIdxs,
		MessageInfos:      file_sf_remotebuild_v1_remotebuild_proto_msgTypes,
	}.Build()
	File_sf_remotebuild_v1_remotebuild_proto = out.File
	file_sf_remotebuild_v1_remotebuild_proto_rawDesc = nil
	file_sf_remotebuild_v1_remotebuild_proto_goTypes = nil
	file_sf_remotebuild_v1_remotebuild_proto_depIdxs = nil
}
