package keymap

import "github.com/charmbracelet/bubbles/key"

var k = key.WithKeys("")
var EscapeModal = key.NewBinding(key.WithHelp("esc", "Dismiss dialog"), k)
var SearchSwitchJQ = key.NewBinding(key.WithHelp("/", "Switch to jq search mode (on empty line)"), k)
var GeneralSearchEnter = key.NewBinding(key.WithHelp("enter", "Search"), k)
var EnterAcceptValue = key.NewBinding(key.WithHelp("enter", "Accept value"), k)
var ModSearchEnter = key.NewBinding(key.WithHelp("enter", "Use module"), k)
var GeneralSearchBackspace = key.NewBinding(key.WithHelp("backspace", "Cancel search with empty box"), k)
var MainNavigation = key.NewBinding(key.WithHelp("←/→/(s-)tab", "Main tabs nav"), k)
var PrevNextModule = key.NewBinding(key.WithHelp("u/i", "Modules nav"), k)
var PrevNextBlock = key.NewBinding(key.WithHelp("o/p", "Blocks nav"), k)
var Search = key.NewBinding(key.WithHelp("/", "Search"), k)
var PrevNextMatchedBlock = key.NewBinding(key.WithHelp("O/P", "Matched blocks nav"), k)
var ModuleSearch = key.NewBinding(key.WithHelp("m", "Select module"), k)
var RestartStream = key.NewBinding(key.WithHelp("r", "Restart stream"), k)
var Build = key.NewBinding(key.WithHelp("b", "Build Substreams"), k)
var UpDown = key.NewBinding(key.WithHelp("↑/↓/k/j", "Up/Down"), k)
var LeftRight = key.NewBinding(key.WithHelp("←/→/h/l", "Left/Right"), k)
var UpDownPage = key.NewBinding(key.WithHelp("pgup/pgdn", "Up/Down page"), k)
var ToggleLogs = key.NewBinding(key.WithHelp("L", "Toggle logs"), k)
var ToggleBytesFormat = key.NewBinding(key.WithHelp("F", "Bytes format display"), k)
var Help = key.NewBinding(key.WithHelp("?", "Show more"), k)
var PrevNextSearchResult = key.NewBinding(key.WithHelp("n/N", "Prev/next search match"), k)
var Quit = key.NewBinding(key.WithHelp("q", "Quit"), k)
var ToggleProgressDisplayMode = key.NewBinding(key.WithHelp("m", "Toggle display mode"), k)
var GoToBlock = key.NewBinding(key.WithHelp("=", "Go to block"), k)
var ModGraphView = key.NewBinding(key.WithHelp("M", "Toggle module graph view"), k)
