version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns: ["*"]
  - package-ecosystem: "gomod"
    directory: "/tests_e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns: ["*"]
