root: ./docs/

structure:
  summary: SUMMARY.md

redirects:
  /concepts-and-fundamentals/benefits: /README
  /concepts-and-fundamentals/fundamentals: /README
  /concepts-and-fundamentals/modules: /new/common/manifest-modules
  /developers-guide/creating-protobuf-schema: /new/develop/creating-protobuf-schemas
  /developers-guide/creating-your-manifest: /new/common/manifest-modules
  /developers-guide/gui: /new/references/gui
  /developers-guide/installation-requirements: /new/common/installing-the-cli
  /developers-guide/overview: /new/develop/init-project
  /developers-guide/parallel-execution: /new/develop/architecture
  /developers-guide/running-substreams: /new/common/running-substreams
  /developers-guide/modules/inputs: /new/develop/modules/inputs
  /developers-guide/modules/outputs: /new/develop/modules/outputs
  /developers-guide/modules/setting-up-handlers: /new/develop/modules/setting-up-handlers
  /developers-guide/modules/types: /new/develop/modules/types
  /developers-guide/modules/writing-module-handlers: /new/develop/modules/writing-module-handlers
  /developers-guide/cookbook/advanced-params: /new/develop/parameterized-modules
  /developers-guide/cookbook/aggregation-windows: /new/develop/modules/aggregation-windows
  /developers-guide/cookbook/dynamic-data-sources: /new/develop/modules/dynamic-data-sources
  /developers-guide/cookbook/factory-params: /new/develop/parameterized-modules
  /developers-guide/cookbook/keys-in-stores: /new/develop/modules/keys-in-stores
  /developers-guide/sink-targets/substreams-powered-subgraph: /new/how-to-guides/sinks/subgraph/subgraph
  /developers-guide/sink-targets/substreams-sink-sql: /new/how-to-guides/sinks/sql/sql-sink
  /developers-guide/sink-targets/substreams-sink-files: /new/consume/other-sinks/files
  /developers-guide/sink-targets/substreams-sink-kv: /new/consume/other-sinks/kv
  /developers-guide/sink-targets/substreams-sink-mongodb: /new/consume/other-sinks/mongodb
  /developers-guide/sink-targets/substreams-sink-prometheus: /new/consume/other-sinks/prometheus
  /getting-started/installing-the-cli: /new/common/installing-the-cli
  /getting-started/quickstart: /new/develop/init-project
  /references-and-specs/chains-and-endpoints: /new/references/chains-and-endpoints
  /references-and-specs/command-line-interface: /new/references/command-line-interface
  /references-and-specs/examples: /new/tutorials/overview
  /references-and-specs/gui: /new/references/gui
  /references-and-specs/faq: /new/references/faq
  /references-and-specs/manifests: /new/references/manifests
  /references-and-specs/packages: /new/common/packages
  /references-and-specs/rust-crates: /new/develop/rust-crates
  /glossary/glossary: /new/references/glossary
  /quick-access/change-log: /new/references/change-log
  /tutorials/from-ethereum-address-to-sql: /new/consume/sql/deployable-services/remote-service
  /tutorials/substreams-sql: /new/consume/sql/deployable-services/local-service
  /tutorials/exploring-ethereum: /new/tutorials/evm/exploring-ethereum
  /tutorials/exploring-ethereum/overview: /new/tutorials/evm/exploring-ethereum
  /tutorials/exploring-ethereum/map_block_meta_module: /new/tutorials/evm/exploring-ethereum/map_block_meta_module
  /tutorials/exploring-ethereum/map_filter_transactions_module: /new/tutorials/evm/exploring-ethereum/map_filter_transactions_module
  /tutorials/exploring-ethereum/map_contract_events_module: /new/tutorials/evm/exploring-ethereum/map_contract_events_module
  /tutorials/rust/overview: /new/tutorials/rust/overview
  /tutorials/rust: /new/how-to-guides/using-rust-proto/rust/rust
  /tutorials/rust/option: /new/how-to-guides/using-rust-proto/rust/option
  /tutorials/rust/result: /new/how-to-guides/using-rust-proto/rust/result
  /tutorials/eth-calls: /new/how-to-guides/using-rust-proto/eth-calls/eth-calls
  /documentation/consume/other-ways-of-consuming: /new/consume/other-sinks
  /documentation/consume/other-ways-of-consuming/kv: /new/consume/other-sinks/kv
  /documentation/consume/other-ways-of-consuming/mongodb: /new/consume/other-sinks/mongodb
  /documentation/consume/other-ways-of-consuming/files: /new/consume/other-sinks/files
  /documentation/consume/other-ways-of-consuming/prometheus: /new/consume/other-sinks/prometheus
  /documentation/consume/other-ways-of-consuming/pubsub: /new/consume/other-sinks/pubsub
  /intro-solana: /new/tutorials/solana
  /intro-injective: /new/tutorials/injective
  /documentation/intro-getting-started: /new/tutorials/intro-to-tutorials
  /documentation/intro-getting-started/intro-evm: /new/tutorials/evm
  /documentation/intro-getting-started/intro-evm/evm-first-sps: /new/tutorials/evm
  /documentation/intro-getting-started/intro-evm/evm-first-sql: /new/tutorials/evm
  /documentation/intro-getting-started/intro-solana: /new/tutorials/solana
  /documentation/intro-getting-started/intro-injective: /new/tutorials/cosmos-compatible/injective
  /documentation/intro-getting-started/intro-injective/injective-first-sql: /new/tutorials/cosmos-compatible/injective
  /documentation/intro-getting-started/intro-injective/injective-first-sps: /new/tutorials/cosmos-compatible/injective
  /documentation/how-to-guides/solana: /new/tutorials/solana
  /documentation/how-to-guides/evm: /new/tutorials/evm
  /documentation/how-to-guides/injective: /new/tutorials/cosmos-compatible/injective
  /how-to-guides/sinks/sql-sink: /new/how-to-guides/sinks/sql/sql
  /how-to-guides/sinks/community-sinks/files: /new/how-to-guides/sinks/files
  /how-to-guides/overview/eth-calls: /new/how-to-guides/develop-your-own-substreams/evm/eth-calls
  /how-to-guides/migrate: /new/how-to-guides/develop-your-own-substreams/solana/migrate-from-yellowstone
  /reference-material/substreams-cli/installing-the-cli: /new/how-to-guides/cli/installing-the-cli
  /tutorials/publish-package: /new/how-to-guides/publish-package
