# syntax=docker/dockerfile:1.2

FROM golang:1.19.2-bullseye AS builder

ARG VERSION

COPY . /work/src

WORKDIR /work/src

RUN \
    /bin/bash -c ": ${VERSION:?Build argument 'VERSION' needs to be set and not null, use '--build-arg VERSION=<Value>' when building the image}" && \
    go build -ldflags "-s -w -X main.version='${VERSION}'" ./cmd/substreams && \
    chmod a+x substreams
