// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/substreams/rpc/v3/service.proto

package pbsubstreamsrpcv3

import (
	_ "github.com/streamingfast/pbgo/sf/firehose/v2"
	v2 "github.com/streamingfast/substreams/pb/sf/substreams/rpc/v2"
	v1 "github.com/streamingfast/substreams/pb/sf/substreams/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request is the input message for the `Stream.Blocks` RPC in the v3 API. It extends the
// v2 request by accepting a full `.spkg` package instead of raw module definitions, and
// adds support for parameter overrides and network selection applied server-side.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If positive, the absolute block number at which to start streaming (inclusive).
	// If 0, streaming starts at the first streamable block of the chain.
	// If negative, the start block is resolved relative to the chain HEAD at the time of
	// the request (e.g., -10 starts 10 blocks before the current HEAD).
	StartBlockNum int64 `protobuf:"varint,1,opt,name=start_block_num,json=startBlockNum,proto3" json:"start_block_num,omitempty"`
	// Cursor returned by a previous `BlockScopedData.cursor` or
	// `BlockUndoSignal.last_valid_cursor`. When provided, streaming resumes from the exact
	// position the cursor points to, taking precedence over `start_block_num`. Use this to
	// implement reliable exactly-once resumption after disconnections or forks.
	StartCursor string `protobuf:"bytes,2,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	// If non-zero, streaming stops *before* reaching this block number (exclusive upper bound).
	// If zero, the stream continues indefinitely, following the chain HEAD in real-time.
	StopBlockNum uint64 `protobuf:"varint,3,opt,name=stop_block_num,json=stopBlockNum,proto3" json:"stop_block_num,omitempty"`
	// With final_block_only, you only receive blocks that are irreversible:
	// 'final_block_height' will be equal to current block and no 'undo_signal' will ever be sent
	FinalBlocksOnly bool `protobuf:"varint,4,opt,name=final_blocks_only,json=finalBlocksOnly,proto3" json:"final_blocks_only,omitempty"`
	// Substreams has two mode when executing your module(s) either development mode or production
	// mode. Development and production modes impact the execution of Substreams, important aspects
	// of execution include:
	// * The time required to reach the first byte.
	// * The speed that large ranges get executed.
	// * The module logs and outputs sent back to the client.
	//
	// By default, the engine runs in developer mode, with richer and deeper output. Differences
	// between production and development modes include:
	// * Forward parallel execution is enabled in production mode and disabled in development mode
	// * The time required to reach the first byte in development mode is faster than in production mode.
	//
	// Specific attributes of development mode include:
	// * The client will receive all of the executed module's logs.
	// * It's possible to request specific store snapshots in the execution tree (via `debug_initial_store_snapshot_for_modules`).
	// * Multiple module's output is possible.
	//
	// With production mode`, however, you trade off functionality for high speed enabling forward
	// parallel execution of module ahead of time.
	ProductionMode bool `protobuf:"varint,5,opt,name=production_mode,json=productionMode,proto3" json:"production_mode,omitempty"`
	// Name of the map module whose output should be streamed back to the client. Must be a
	// `map` module defined in the provided `package`. Only one output module is supported per request.
	OutputModule string `protobuf:"bytes,6,opt,name=output_module,json=outputModule,proto3" json:"output_module,omitempty"`
	// The full .spkg package containing the module definitions and their code.
	Package *v1.Package `protobuf:"bytes,7,opt,name=package,proto3" json:"package,omitempty"`
	// Module parameter overrides to apply to the package server-side. Keys are module names, values are parameter strings.
	Params map[string]string `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Network name to select when the package supports multiple networks (e.g., "mainnet", "sepolia").
	Network string `protobuf:"bytes,9,opt,name=network,proto3" json:"network,omitempty"`
	// Available only in developer mode
	DebugInitialStoreSnapshotForModules []string `protobuf:"bytes,10,rep,name=debug_initial_store_snapshot_for_modules,json=debugInitialStoreSnapshotForModules,proto3" json:"debug_initial_store_snapshot_for_modules,omitempty"`
	// When true, prepares the stores and caches on the server without sending any module
	// output. Only progress messages and minimal clock/cursor data are returned. Useful for
	// pre-warming caches (e.g., to reduce latency for a subsequent real request) without
	// incurring the cost of transmitting full block data.
	NoopMode bool `protobuf:"varint,11,opt,name=noop_mode,json=noopMode,proto3" json:"noop_mode,omitempty"`
	// If set, the engine will reject a request if the number of blocks to process (including preparing the stores) is above this limit.
	// Useful as a safeguard for managing costs
	LimitProcessedBlocks uint64 `protobuf:"varint,12,opt,name=limit_processed_blocks,json=limitProcessedBlocks,proto3" json:"limit_processed_blocks,omitempty"`
	// Available only in developer mode
	// If set, the server will only send the output of these modules.
	// If unset, all the outputs are sent.
	// This allows the user to reduce the payload in dev mode, while still getting some extra debugging information
	DevOutputModules []string `protobuf:"bytes,13,rep,name=dev_output_modules,json=devOutputModules,proto3" json:"dev_output_modules,omitempty"`
	// Interval between progress messages, in milliseconds (minimum: 500). When left at 0, the
	// interval widens with the age of the request: 1s for the first minute, 10s up to 5 minutes,
	// 30s up to 10 minutes, 60s beyond that.
	ProgressMessagesIntervalMs uint64 `protobuf:"varint,14,opt,name=progress_messages_interval_ms,json=progressMessagesIntervalMs,proto3" json:"progress_messages_interval_ms,omitempty"`
	// If true, blocks close to head will be sent in "partials" as soon as we get them.
	// This means that you will get different versions of the same block number, each an incomplete increment
	// Other blocks will be sent completely (older blocks, or blocks for which the provider did not get a partial in time)
	PartialBlocks bool `protobuf:"varint,16,opt,name=partial_blocks,json=partialBlocks,proto3" json:"partial_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_sf_substreams_rpc_v3_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_rpc_v3_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sf_substreams_rpc_v3_service_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetStartBlockNum() int64 {
	if x != nil {
		return x.StartBlockNum
	}
	return 0
}

func (x *Request) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

func (x *Request) GetStopBlockNum() uint64 {
	if x != nil {
		return x.StopBlockNum
	}
	return 0
}

func (x *Request) GetFinalBlocksOnly() bool {
	if x != nil {
		return x.FinalBlocksOnly
	}
	return false
}

func (x *Request) GetProductionMode() bool {
	if x != nil {
		return x.ProductionMode
	}
	return false
}

func (x *Request) GetOutputModule() string {
	if x != nil {
		return x.OutputModule
	}
	return ""
}

func (x *Request) GetPackage() *v1.Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *Request) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Request) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Request) GetDebugInitialStoreSnapshotForModules() []string {
	if x != nil {
		return x.DebugInitialStoreSnapshotForModules
	}
	return nil
}

func (x *Request) GetNoopMode() bool {
	if x != nil {
		return x.NoopMode
	}
	return false
}

func (x *Request) GetLimitProcessedBlocks() uint64 {
	if x != nil {
		return x.LimitProcessedBlocks
	}
	return 0
}

func (x *Request) GetDevOutputModules() []string {
	if x != nil {
		return x.DevOutputModules
	}
	return nil
}

func (x *Request) GetProgressMessagesIntervalMs() uint64 {
	if x != nil {
		return x.ProgressMessagesIntervalMs
	}
	return 0
}

func (x *Request) GetPartialBlocks() bool {
	if x != nil {
		return x.PartialBlocks
	}
	return false
}

var File_sf_substreams_rpc_v3_service_proto protoreflect.FileDescriptor

const file_sf_substreams_rpc_v3_service_proto_rawDesc = "" +
	"\n" +
	"\"sf/substreams/rpc/v3/service.proto\x12\x14sf.substreams.rpc.v3\x1a\x19google/protobuf/any.proto\x1a\x1dsf/firehose/v2/firehose.proto\x1a\"sf/substreams/rpc/v2/service.proto\x1a\x1csf/substreams/v1/clock.proto\x1a\x1esf/substreams/v1/modules.proto\x1a\x1esf/substreams/v1/package.proto\"\x89\x06\n" +
	"\aRequest\x12&\n" +
	"\x0fstart_block_num\x18\x01 \x01(\x03R\rstartBlockNum\x12!\n" +
	"\fstart_cursor\x18\x02 \x01(\tR\vstartCursor\x12$\n" +
	"\x0estop_block_num\x18\x03 \x01(\x04R\fstopBlockNum\x12*\n" +
	"\x11final_blocks_only\x18\x04 \x01(\bR\x0ffinalBlocksOnly\x12'\n" +
	"\x0fproduction_mode\x18\x05 \x01(\bR\x0eproductionMode\x12#\n" +
	"\routput_module\x18\x06 \x01(\tR\foutputModule\x123\n" +
	"\apackage\x18\a \x01(\v2\x19.sf.substreams.v1.PackageR\apackage\x12A\n" +
	"\x06params\x18\b \x03(\v2).sf.substreams.rpc.v3.Request.ParamsEntryR\x06params\x12\x18\n" +
	"\anetwork\x18\t \x01(\tR\anetwork\x12U\n" +
	"(debug_initial_store_snapshot_for_modules\x18\n" +
	" \x03(\tR#debugInitialStoreSnapshotForModules\x12\x1b\n" +
	"\tnoop_mode\x18\v \x01(\bR\bnoopMode\x124\n" +
	"\x16limit_processed_blocks\x18\f \x01(\x04R\x14limitProcessedBlocks\x12,\n" +
	"\x12dev_output_modules\x18\r \x03(\tR\x10devOutputModules\x12A\n" +
	"\x1dprogress_messages_interval_ms\x18\x0e \x01(\x04R\x1aprogressMessagesIntervalMs\x12%\n" +
	"\x0epartial_blocks\x18\x10 \x01(\bR\rpartialBlocks\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x0f\x10\x102S\n" +
	"\x06Stream\x12I\n" +
	"\x06Blocks\x12\x1d.sf.substreams.rpc.v3.Request\x1a\x1e.sf.substreams.rpc.v2.Response0\x01BOZMgithub.com/streamingfast/substreams/pb/sf/substreams/rpc/v3;pbsubstreamsrpcv3b\x06proto3"

var (
	file_sf_substreams_rpc_v3_service_proto_rawDescOnce sync.Once
	file_sf_substreams_rpc_v3_service_proto_rawDescData []byte
)

func file_sf_substreams_rpc_v3_service_proto_rawDescGZIP() []byte {
	file_sf_substreams_rpc_v3_service_proto_rawDescOnce.Do(func() {
		file_sf_substreams_rpc_v3_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_rpc_v3_service_proto_rawDesc), len(file_sf_substreams_rpc_v3_service_proto_rawDesc)))
	})
	return file_sf_substreams_rpc_v3_service_proto_rawDescData
}

var file_sf_substreams_rpc_v3_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sf_substreams_rpc_v3_service_proto_goTypes = []any{
	(*Request)(nil),     // 0: sf.substreams.rpc.v3.Request
	nil,                 // 1: sf.substreams.rpc.v3.Request.ParamsEntry
	(*v1.Package)(nil),  // 2: sf.substreams.v1.Package
	(*v2.Response)(nil), // 3: sf.substreams.rpc.v2.Response
}
var file_sf_substreams_rpc_v3_service_proto_depIdxs = []int32{
	2, // 0: sf.substreams.rpc.v3.Request.package:type_name -> sf.substreams.v1.Package
	1, // 1: sf.substreams.rpc.v3.Request.params:type_name -> sf.substreams.rpc.v3.Request.ParamsEntry
	0, // 2: sf.substreams.rpc.v3.Stream.Blocks:input_type -> sf.substreams.rpc.v3.Request
	3, // 3: sf.substreams.rpc.v3.Stream.Blocks:output_type -> sf.substreams.rpc.v2.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sf_substreams_rpc_v3_service_proto_init() }
func file_sf_substreams_rpc_v3_service_proto_init() {
	if File_sf_substreams_rpc_v3_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_rpc_v3_service_proto_rawDesc), len(file_sf_substreams_rpc_v3_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_substreams_rpc_v3_service_proto_goTypes,
		DependencyIndexes: file_sf_substreams_rpc_v3_service_proto_depIdxs,
		MessageInfos:      file_sf_substreams_rpc_v3_service_proto_msgTypes,
	}.Build()
	File_sf_substreams_rpc_v3_service_proto = out.File
	file_sf_substreams_rpc_v3_service_proto_goTypes = nil
	file_sf_substreams_rpc_v3_service_proto_depIdxs = nil
}
