// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub event: ::prost::alloc::vec::Vec<Event>,
}
/// Same shape as test.output.Event, annotated for the ClickHouse sink. It is a
/// separate message rather than options on the shared one: the annotations change
/// the module hash, and test.output.Event is what the other e2e modules emit.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// ClickHouse requires the primary key to be a prefix of the sorting key, so
    /// the hash leads and the block number follows.
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub evt_from: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub evt_to: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="5")]
    pub fee: u64,
}
// @@protoc_insertion_point(module)
