// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sf/substreams/rpc/v4/estimate.proto

package pbsubstreamsrpcv4connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v4 "github.com/streamingfast/substreams/pb/sf/substreams/rpc/v4"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EstimatorName is the fully-qualified name of the Estimator service.
	EstimatorName = "sf.substreams.rpc.v4.Estimator"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EstimatorEstimateProcedure is the fully-qualified name of the Estimator's Estimate RPC.
	EstimatorEstimateProcedure = "/sf.substreams.rpc.v4.Estimator/Estimate"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	estimatorServiceDescriptor        = v4.File_sf_substreams_rpc_v4_estimate_proto.Services().ByName("Estimator")
	estimatorEstimateMethodDescriptor = estimatorServiceDescriptor.Methods().ByName("Estimate")
)

// EstimatorClient is a client for the sf.substreams.rpc.v4.Estimator service.
type EstimatorClient interface {
	// Estimate samples the requested range and returns a cost estimate. The stream emits
	// `EstimateProgress` messages while the sample jobs run, then exactly one `Estimate`
	// message before completing. No module output is ever sent.
	Estimate(context.Context, *connect.Request[v4.EstimateRequest]) (*connect.ServerStreamForClient[v4.EstimateResponse], error)
}

// NewEstimatorClient constructs a client for the sf.substreams.rpc.v4.Estimator service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEstimatorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EstimatorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &estimatorClient{
		estimate: connect.NewClient[v4.EstimateRequest, v4.EstimateResponse](
			httpClient,
			baseURL+EstimatorEstimateProcedure,
			connect.WithSchema(estimatorEstimateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// estimatorClient implements EstimatorClient.
type estimatorClient struct {
	estimate *connect.Client[v4.EstimateRequest, v4.EstimateResponse]
}

// Estimate calls sf.substreams.rpc.v4.Estimator.Estimate.
func (c *estimatorClient) Estimate(ctx context.Context, req *connect.Request[v4.EstimateRequest]) (*connect.ServerStreamForClient[v4.EstimateResponse], error) {
	return c.estimate.CallServerStream(ctx, req)
}

// EstimatorHandler is an implementation of the sf.substreams.rpc.v4.Estimator service.
type EstimatorHandler interface {
	// Estimate samples the requested range and returns a cost estimate. The stream emits
	// `EstimateProgress` messages while the sample jobs run, then exactly one `Estimate`
	// message before completing. No module output is ever sent.
	Estimate(context.Context, *connect.Request[v4.EstimateRequest], *connect.ServerStream[v4.EstimateResponse]) error
}

// NewEstimatorHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEstimatorHandler(svc EstimatorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	estimatorEstimateHandler := connect.NewServerStreamHandler(
		EstimatorEstimateProcedure,
		svc.Estimate,
		connect.WithSchema(estimatorEstimateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/sf.substreams.rpc.v4.Estimator/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EstimatorEstimateProcedure:
			estimatorEstimateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEstimatorHandler returns CodeUnimplemented from all methods.
type UnimplementedEstimatorHandler struct{}

func (UnimplementedEstimatorHandler) Estimate(context.Context, *connect.Request[v4.EstimateRequest], *connect.ServerStream[v4.EstimateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sf.substreams.rpc.v4.Estimator.Estimate is not implemented"))
}
