name: Buf

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - develop
      - release/v*
      - feature/*

jobs:
  buf:
    runs-on: ubuntu-24.04
    if: "${{ !startsWith(github.event.head_commit.message, 'GitBook: [#') }}"
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Lint protos
        # TODO: Consider enabling this after fixing or ignoring the current linting errors?
        if: false
        uses: bufbuild/buf-lint-action@v1

      - name: Check for breaking changes
        if: github.event_name == 'pull_request'
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: "https://github.com/${{ github.repository }}.git#branch=${{ github.base_ref }}"

      - name: Push to Buf registry
        if: github.event_name != 'pull_request'
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          ARGS=""

          # Use --draft for non-tag pushes
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v ]]; then
            ARGS="--draft"
          fi

          # Add --label with the tag name for tag pushes
          if [[ "$GITHUB_REF" =~ ^refs/tags/ ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            ARGS="$ARGS --label $TAG_NAME"
          fi

          echo "Running: buf push proto $ARGS"
          buf push proto $ARGS
