name: Secret Scanning Check
on:
  pull_request:
  push:
    tags:
      - "v*"
    branches:
      - "develop"

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Run Secret Scanning Review
        uses: advanced-security/secret-scanning-review-action@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true # This turns it into a hard status check
