name: Secret Scanning Check
on:
  pull_request:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Run Secret Scanning Review
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: advanced-security/secret-scanning-review-action@v2.2.4
        with:
          token: ${{ secrets.SECRETS_ALERTS }}
          fail-on-alert: true # This turns it into a hard status check
          runtime: python
